version: 0.0
os: linux
files:
  - source: /
    destination: /home/
hooks:
  BeforeInstall:
    - location: deploy_script/install.sh
      timeout: 1200
      runas: root
file_exists_behavior: OVERWRITE
