version: 0.2
phases:
  build:
    commands:
       - npm i react-scripts
       - npm run build
       - zip -r demo.zip public/index.html appspec.yml deploy_script
artifacts:
  files:
    - '**/deploy_script'
    - '**/public/index.html'
    - '**/appspec.yml'
